### ISSUE TITLE
To-Do for First Official ALPHA Release

### ISSUE THREAD

**Issue by LaxSlash** [LaxSlash/applications_ext#1]
- [x] ~~Implement permissions checking~~
- [ ] Add ACP Module
- [ ] Create vote statistics page
- [ ] Add in applications state and locked/unlocked verification
- [ ] Integrate Notifications
- [ ] Code for an Applications Deletion Proceedure
  - [ ] COMPLETELY REWRITE ENTIRE DELETIONS HANDLING SYSTEM!!!!!
- [ ] CState Username Errors and proper Error Handling
- [x] ~~Application viewing and submission permissions~~
- [ ] Effectively integrate the can_edit, can_withdraw and can_delete permissions to the post/vote editing templates
- [ ] Upload to GitHub Repo
- [ ] Upload/create a demo site
- [x] ~~Comment all main_listener functions~~
- [ ] Add a Notes Field to CSTATE. The default Value should be "Application State changed from (State Name) to (State Name) by Username.
- [ ] Add a poll like Votes Meter on the top of application threads.
- [ ] Vote edits logging page
- [ ] State changes logging page
- [ ] Add/implement a "Add User Note" option on a CState.
- [ ] Go through all files, change includes, requires, include_onces and require_onces to the proper dependencies.
- [x] ~~Fix dependencies in the files.~~
- [ ] Change all '1's/'0's to be true/false (Template and PHP)
- [ ] Add checks when an application is created, edited and submitted that the forum selected for either it or the default state is an applications forum.
- [ ] Create "State Enabled/Disabled" checks and other state checks on forum submissions
- [ ] Work out Sorting of Applications and Forums in Drop Downs
- [ ] Add Error Handling
  - [ ] Application State Forum is npo longer an applications form on submission
  - [ ] Application Default State is Disabled on Submission
  - [ ] Application Default State is no longer existant on Submission
  - [ ] No suitable application forums exist on application state edit/creation
  - [ ] No suitable application forums exist on application edit/creation
- [ ] For Add Applications Page
  - [ ] Add Group Permissions Area
  - [ ] Create Posting Template
